# SPDX-FileCopyrightText: 2013 The freestyle-hid Authors
#
# SPDX-License-Identifier: 0BSD

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.0
    hooks:
      - id: isort
        additional_dependencies:
          - toml
